# Basic Neural Network
## Keras

In [47]:
import warnings
warnings.filterwarnings('ignore')

In [6]:
# import libraries
import numpy as np
from numpy import genfromtxt

In [7]:
# load the dataset
data = genfromtxt('bank_note_data.txt', delimiter=',')
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [8]:
labels = data[:,4]
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [9]:
features = data[:,0:4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [10]:
X = features
y = labels

### Train Test Split

In [11]:
from sklearn.model_selection import train_test_split

train --- validation/dev-set --- test

80/20 - 10000 | 80000

Deep learning model - 10000000 - millions and billions of data\
1000000 weights, biases - these models take a lot of time to train\
99.5 | 0.25 | 0.25

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [13]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [14]:
X_test

array([[ 1.5691  ,  6.3465  , -0.1828  , -2.4099  ],
       [-0.27802 ,  8.1881  , -3.1338  , -2.5276  ],
       [ 0.051979,  7.0521  , -2.0541  , -3.1508  ],
       ...,
       [ 3.5127  ,  2.9073  ,  1.0579  ,  0.40774 ],
       [ 5.504   , 10.3671  , -4.413   , -4.0211  ],
       [-0.2062  ,  9.2207  , -3.7044  , -6.8103  ]])

In [15]:
y_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
       1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 1., 0., 1., 0.

### Standardizing the Data

In [16]:
from sklearn.preprocessing import MinMaxScaler

In [17]:
scaler_object = MinMaxScaler()

In [18]:
scaler_object.fit(X_train)

MinMaxScaler()

In [19]:
scaled_X_train = scaler_object.transform(X_train)

In [20]:
scaled_X_test = scaler_object.transform(X_test)

In [21]:
scaled_X_train

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

In [22]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

### Building the model

In [23]:
# !pip install keras

In [24]:
# !pip install tensorflow

In [26]:
from keras.models import Sequential
from keras.layers import Dense

In [28]:
# initializing the model
model = Sequential()

model.add(Dense(4, input_dim=4, activation='relu'))

model.add(Dense(8, activation='relu'))

model.add(Dense(1, activation='sigmoid'))

### Compile the model

In [30]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [32]:
model.fit(scaled_X_train , y_train , epochs = 10 , verbose = 2)

Epoch 1/10
29/29 - 0s - loss: 0.5438 - accuracy: 0.8052 - 259ms/epoch - 9ms/step
Epoch 2/10
29/29 - 0s - loss: 0.5185 - accuracy: 0.8433 - 154ms/epoch - 5ms/step
Epoch 3/10
29/29 - 0s - loss: 0.4954 - accuracy: 0.8629 - 163ms/epoch - 6ms/step
Epoch 4/10
29/29 - 0s - loss: 0.4727 - accuracy: 0.8749 - 129ms/epoch - 4ms/step
Epoch 5/10
29/29 - 0s - loss: 0.4522 - accuracy: 0.8792 - 172ms/epoch - 6ms/step
Epoch 6/10
29/29 - 0s - loss: 0.4335 - accuracy: 0.8836 - 146ms/epoch - 5ms/step
Epoch 7/10
29/29 - 0s - loss: 0.4154 - accuracy: 0.8879 - 162ms/epoch - 6ms/step
Epoch 8/10
29/29 - 0s - loss: 0.3992 - accuracy: 0.8879 - 144ms/epoch - 5ms/step
Epoch 9/10
29/29 - 0s - loss: 0.3842 - accuracy: 0.8912 - 179ms/epoch - 6ms/step
Epoch 10/10
29/29 - 0s - loss: 0.3706 - accuracy: 0.9021 - 146ms/epoch - 5ms/step


In [33]:
scaled_X_test

array([[0.62098955, 0.75284662, 0.21900753, 0.5730998 ],
       [0.48778602, 0.82175665, 0.09174727, 0.56211079],
       [0.51158363, 0.77924916, 0.13830875, 0.50392598],
       ...,
       [0.76115065, 0.62415668, 0.27251204, 0.83616757],
       [0.9047516 , 0.90329171, 0.03658247, 0.42267079],
       [0.49296526, 0.86039507, 0.06714046, 0.1622583 ]])

In [58]:
model.predict(scaled_X_test)

15/15 [==============================] - 0s 4ms/step


array([[0.18010913],
       [0.4260167 ],
       [0.31396577],
       [0.36279422],
       [0.17889836],
       [0.10805662],
       [0.448189  ],
       [0.08140706],
       [0.16799942],
       [0.4097632 ],
       [0.37344462],
       [0.6123067 ],
       [0.44413465],
       [0.6316132 ],
       [0.7863938 ],
       [0.19269565],
       [0.7628923 ],
       [0.7723571 ],
       [0.7041527 ],
       [0.7304483 ],
       [0.1202985 ],
       [0.30694985],
       [0.7394716 ],
       [0.11329222],
       [0.89947915],
       [0.12209944],
       [0.10759978],
       [0.6835132 ],
       [0.0278148 ],
       [0.05315775],
       [0.40713292],
       [0.31954804],
       [0.35878825],
       [0.92417884],
       [0.8540662 ],
       [0.0836923 ],
       [0.36319315],
       [0.5470902 ],
       [0.6276227 ],
       [0.31064427],
       [0.261417  ],
       [0.41665518],
       [0.561602  ],
       [0.13326576],
       [0.85857826],
       [0.7051648 ],
       [0.7825264 ],
       [0.118

In [35]:
# model.predict_classes(scaled_X_test)

### Evaluate the model

In [36]:
model.metrics_names

['loss', 'accuracy']

In [37]:
model.evaluate(x=scaled_X_test, y=y_test)

15/15 [==============================] - 1s 7ms/step - loss: 0.3591 - accuracy: 0.8985


[0.3591225743293762, 0.8984547257423401]

In [38]:
from sklearn.metrics import confusion_matrix, classification_report

In [39]:
predictions = model.predict(scaled_X_test)
classes_x=np.argmax(predictions,axis=1)

15/15 [==============================] - 0s 6ms/step


In [40]:
classes_x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [41]:
confusion_matrix(y_test, classes_x)

array([[257,   0],
       [196,   0]], dtype=int64)

In [48]:
print(classification_report(y_test, classes_x))

              precision    recall  f1-score   support

         0.0       0.57      1.00      0.72       257
         1.0       0.00      0.00      0.00       196

    accuracy                           0.57       453
   macro avg       0.28      0.50      0.36       453
weighted avg       0.32      0.57      0.41       453



In [49]:
predictions = (model.predict(scaled_X_test) > 0.5).astype("int32")

15/15 [==============================] - 0s 5ms/step


In [50]:
confusion_matrix(y_test, predictions)

array([[245,  12],
       [ 34, 162]], dtype=int64)

In [51]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.88      0.95      0.91       257
         1.0       0.93      0.83      0.88       196

    accuracy                           0.90       453
   macro avg       0.90      0.89      0.89       453
weighted avg       0.90      0.90      0.90       453



### Save and load the model

In [52]:
model.save('mydeeplearningmodel')

INFO:tensorflow:Assets written to: mydeeplearningmodel\assets


INFO:tensorflow:Assets written to: mydeeplearningmodel\assets


In [53]:
from keras.models import load_model

In [ ]:
newmodel = load_model('mydeeplearningmodel')

In [55]:
newmodel.predict(X_test)

15/15 [==============================] - 0s 7ms/step


array([[4.45049373e-05],
       [9.99985099e-01],
       [9.94284213e-01],
       [9.99987662e-01],
       [6.76522090e-04],
       [6.29058122e-05],
       [9.96482193e-01],
       [1.72049611e-10],
       [9.51735001e-06],
       [4.35313061e-02],
       [2.86506419e-03],
       [9.99851048e-01],
       [6.98215723e-01],
       [6.98215723e-01],
       [8.33339810e-01],
       [4.78353089e-04],
       [6.98215723e-01],
       [6.98215723e-01],
       [6.98215723e-01],
       [6.98215723e-01],
       [3.20176659e-05],
       [7.44950818e-03],
       [6.98215723e-01],
       [1.66213923e-07],
       [1.00000000e+00],
       [3.70609121e-09],
       [1.37502463e-08],
       [6.98215723e-01],
       [6.32762453e-15],
       [1.11031356e-12],
       [9.97968018e-01],
       [2.88914167e-03],
       [1.32115036e-01],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.49523283e-09],
       [2.13816855e-03],
       [5.91531634e-01],
       [9.99825001e-01],
       [6.32774027e-04],
